akhq:
  connections:
    hands-on-kafka:
      properties:
        bootstrap.servers: "kafka:29092"
      schema-registry:
        url: "http://schema-registry:8080/apis/ccompat/v7"
      connect:
        - name: debezium
          url: "http://debezium:8083"
